"""Tests for _2024/_8/main.py functions."""

import pytest
from helpers.array_helper import Board
from _2024._8.main import (
    part1,
    part2,
)


def create_board_from_string(board_str: str) -> Board:
    """Helper function to create a Board from a string representation."""
    lines = board_str.strip().split('\n')
    return Board([list(line) for line in lines])


class TestPart1:
    """Tests for part1 function."""

    def test_given_data(self):
        """Test with the provided test data."""
        grid_str = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""
        
        board = create_board_from_string(grid_str)
        result = part1(board)
        assert result == 14


class TestPart2:
    """Tests for part2 function."""

    def test_given_data(self):
        """Test with the provided test data."""
        grid_str = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""
        
        board = create_board_from_string(grid_str)
        result = part2(board)
        assert result == 34

